#!/bin/bash


sudo apt-get update
sudo apt-get upgrade -y


sudo apt-get install -y wget apt-transport-https software-properties-common


wget https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo rm packages-microsoft-prod.deb


sudo apt-get update
sudo apt-get install -y dotnet-sdk-8.0


sudo snap install --classic code


dotnet --version
code --version


